server:
  port: 8072
spring:
  data:
    redis:
     connection-timeout: 2s
     host: localhost
     port: 6379
     timout: 1s 
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false 
          lowerCaseServiceId: true
      httpclient:
        connection-timeout: 4000
        response-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

logging:
 level:
  com:
   learn:
    gatewayserver: DEBUG
  org.springframework.cloud.gateway: DEBUG
  org.springframework.boot.actuate: DEBUG

build:
  version: 1

info:
  app:
    name: gatewayserver
    description: Learning Account
    version: 1.0

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
 configs:
  default:
   slidingWindowSize: 10
   permittedNumberOfCallsInHalfOpenState: 2
   failureRateThreshold: 50
   waitDurationInOpenState: 10000

  