spring:
 application:
  name: eurekaserver
 config: 
  import: "optional:configserver:http://localhost:8071/"

eureka:
 instance:
  lease-renewal-interval-in-second: 30
  hostname: localhost
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
 port : 8761
 
management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  readiness-state: true
   enabled:true
  liveness-state:
   enabled:true
 endpoint:
  health:
   probes:
    enabled: true   